[package]
name = "Thrigger_Primes"
version = "0.1.0"
authors = ["Thrigger"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
